import { extractCanonicalUrl, extractHeadings, extractJsonLdBlocks, extractLinks, extractMetaContent, extractTitle, stripTags } from "@/lib/audit/collectors/shared/html-parse";
import { selectSearchProfile } from "@/lib/audit/search-profiles";
import type { AeoCategoryKey, AeoCategoryResult, AeoQuestionResult, AeoSnapshot } from "./types";

export const AEO_WEIGHTS: Record<AeoCategoryKey, number> = { business_identity: 15, services_offerings: 15, location_service_area: 10, structured_data: 15, answer_friendly_content: 20, expertise_trust: 10, crawlability: 5, content_structure: 10 };
const LABELS: Record<AeoCategoryKey, string> = { business_identity: "Business identity", services_offerings: "Services & offerings", location_service_area: "Location & service area", structured_data: "Structured data", answer_friendly_content: "Answer-friendly content", expertise_trust: "Expertise & trust", crawlability: "Crawlability & discoverability", content_structure: "Content structure" };
const QUESTIONS: Record<string, string[]> = {
  financial_advisor: ["What services do you provide?", "Who do you work with?", "Do you offer retirement planning?", "How does financial planning work?", "How do I get started?", "Where are you located?", "What credentials do your advisors have?"],
  dentist: ["Are you accepting new patients?", "What services do you provide?", "Do you accept insurance?", "How do I schedule?", "What should a new patient expect?", "Where are you located?"],
  fitness_gym: ["What types of training do you offer?", "Who can join?", "How much does training cost?", "How do I book?", "What are your hours?", "Where are you located?"],
  sports_training: ["What types of training do you offer?", "Who do you train?", "How do I book?", "Where are you located?", "What should I expect?"],
  salon: ["What services do you provide?", "How do I book?", "How much do services cost?", "Where are you located?"],
  restaurant: ["What do you serve?", "What are your hours?", "Where are you located?", "How do I contact you?"],
  coffee_shop: ["What do you serve?", "What are your hours?", "Where are you located?", "How do I contact you?"],
  professional_services: ["What services do you provide?", "Who do you work with?", "How do I get started?", "Where are you located?", "What should I expect?"],
  generic_local_business: ["What services do you provide?", "Who do you serve?", "How do I get started?", "Where are you located?", "What are your hours?"]
};

function textOf(html: string) { return stripTags(html).replace(/\s+/g, " ").trim(); }
function has(html: string, pattern: RegExp) { return pattern.test(html) || pattern.test(textOf(html)); }
function schemaNodes(html: string) { return extractJsonLdBlocks(html).flatMap((block) => { if (!block || typeof block !== "object") return []; const value = block as Record<string, unknown>; return Array.isArray(value["@graph"]) ? value["@graph"].filter((node): node is Record<string, unknown> => Boolean(node && typeof node === "object")) : [value]; }); }
function schemaTypes(nodes: Record<string, unknown>[]) { return nodes.flatMap((node) => Array.isArray(node["@type"]) ? node["@type"].filter((type): type is string => typeof type === "string") : typeof node["@type"] === "string" ? [node["@type"]] : []); }
function scoreCategory(key: AeoCategoryKey, checks: Array<{ ok: boolean; evidence: string }>): AeoCategoryResult { const passed = checks.filter((check) => check.ok).length; return { key, label: LABELS[key], score: Math.round((passed / Math.max(1, checks.length)) * 100), passed, failed: checks.length - passed, evidence: checks.map((check) => `${check.ok ? "Pass" : "Needs attention"}: ${check.evidence}`) }; }

export function analyzeAeoReadiness(input: { html: string; businessName?: string | null; market?: string | null }): AeoSnapshot {
  const html = input.html;
  const visible = textOf(html);
  const headings = [...extractHeadings(html, 1), ...extractHeadings(html, 2), ...extractHeadings(html, 3)];
  const links = extractLinks(html);
  const nodes = schemaNodes(html);
  const types = schemaTypes(nodes);
  const profile = selectSearchProfile({ businessName: input.businessName ?? null, services: headings, content: visible });
  const phone = /(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}/.test(visible);
  const email = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i.test(visible);
  const hasAddress = /\b(?:street|st\.?|avenue|ave\.?|road|rd\.?|indianapolis|indiana|in\s*\d{5})\b/i.test(visible);
  const identity = scoreCategory("business_identity", [{ ok: Boolean(input.businessName || nodes.some((node) => typeof node.name === "string")), evidence: "Business name is stated in the page or structured data." }, { ok: Boolean(types.some((type) => /Organization|Business|Service|Person/.test(type))), evidence: "A recognizable business entity type is present." }, { ok: phone, evidence: phone ? "Phone information is visible." : "Phone information was not detected." }, { ok: email, evidence: email ? "Email information is visible." : "Email information was not detected." }, { ok: has(html, /about|our story|who we are/i), evidence: "About/company information is available." }]);
  const serviceTerms = headings.filter((heading) => /service|solution|training|planning|management|advisor|dentist|fitness|restaurant|coffee|salon|consult/i.test(heading));
  const services = scoreCategory("services_offerings", [{ ok: serviceTerms.length >= 1, evidence: `${serviceTerms.length} service-oriented heading(s) detected.` }, { ok: serviceTerms.length >= 2, evidence: "More than one service or offering is described." }, { ok: links.some((link) => /service|solution|training|program|offer/i.test(`${link.href} ${link.text}`)), evidence: "Service-related HTML links are present." }, { ok: visible.length >= 800, evidence: "The page contains enough visible text to explain offerings." }]);
  const location = scoreCategory("location_service_area", [{ ok: hasAddress, evidence: hasAddress ? "Location/address language appears on the website." : "Website location evidence was not detected." }, { ok: Boolean(input.market && visible.toLowerCase().includes(input.market.split(",")[0].trim().toLowerCase())), evidence: input.market ? "The entered market appears in website content." : "No audit market was supplied as context." }, { ok: types.some((type) => /LocalBusiness|ProfessionalService|FinancialService|Restaurant|Cafe|Dentist/.test(type)), evidence: "Location-capable structured data is present." }, { ok: links.some((link) => /location|contact|directions|service-area/i.test(`${link.href} ${link.text}`)), evidence: "A location or contact page link is present." }]);
  const usefulTypes = ["Organization", "LocalBusiness", "ProfessionalService", "FinancialService", "Dentist", "HealthAndBeautyBusiness", "SportsActivityLocation", "Restaurant", "CafeOrCoffeeShop", "Person", "Service", "Product", "Offer", "FAQPage", "Article", "BreadcrumbList"];
  const structured = scoreCategory("structured_data", [{ ok: nodes.length > 0, evidence: `${nodes.length} JSON-LD node(s) detected.` }, { ok: types.some((type) => usefulTypes.includes(type)), evidence: "Applicable business/content schema type detected." }, { ok: types.some((type) => /Organization|LocalBusiness|ProfessionalService|FinancialService|Restaurant|Dentist/.test(type)), evidence: "An entity schema type is present." }, { ok: types.includes("Service") || types.includes("Product") || types.includes("Offer"), evidence: "Service or offering structured data detected." }, { ok: types.includes("FAQPage") || types.includes("Article"), evidence: "Answer/content structured data detected." }]);
  const profileQuestions = QUESTIONS[profile.key] ?? QUESTIONS.generic_local_business;
  const faqText = nodes.filter((node) => schemaTypes([node]).includes("FAQPage")).map((node) => JSON.stringify(node)).join(" ");
  const questions: AeoQuestionResult[] = profileQuestions.map((question) => { const terms = question.toLowerCase().replace(/[?]/g, "").split(/\s+/).filter((term) => term.length > 3).slice(0, 4); const matches = terms.filter((term) => visible.toLowerCase().includes(term)).length; const direct = new RegExp(`<h[1-6][^>]*>[^<]*(?:${terms.join("|")})[^<]*<\\/h[1-6]>[\\s\\S]{0,800}`, "i").test(html) || terms.filter((term) => faqText.toLowerCase().includes(term)).length >= 2; return { question, status: direct && matches >= 2 ? "answered" : matches >= 2 ? "partial" : "not_answered" }; });
  const coverage = { answered: questions.filter((question) => question.status === "answered").length, partial: questions.filter((question) => question.status === "partial").length, notAnswered: questions.filter((question) => question.status === "not_answered").length, total: questions.length, questions };
  const answer = scoreCategory("answer_friendly_content", [{ ok: types.includes("FAQPage") || /<h[1-6][^>]*>[^<]*\?[^<]*<\/h[1-6]>/i.test(html), evidence: "Question-oriented content or FAQ structure detected." }, { ok: coverage.answered >= Math.ceil(coverage.total * 0.5), evidence: `${coverage.answered} of ${coverage.total} common questions appear clearly answered.` }, { ok: headings.length >= 3, evidence: "Content uses descriptive headings." }, { ok: /schedule|book|pricing|cost|hours|process|expect/i.test(visible), evidence: "Practical customer information is present." }]);
  const trust = scoreCategory("expertise_trust", [{ ok: has(html, /about|our story|team|founder/i), evidence: "About, team, or organization information detected." }, { ok: has(html, /credential|certif|licensed|experience|years|professional/i), evidence: "Experience, credential, or professional background language detected." }, { ok: has(html, /testimonial|review|case stud|portfolio/i), evidence: "Customer proof or work examples detected." }, { ok: has(html, /privacy/i), evidence: "Privacy information is linked or mentioned." }, { ok: profile.key === "generic_local_business" || !/financial|dentist|medical|legal|therapy/i.test(visible) || has(html, /author|written by|updated/i), evidence: "Industry-appropriate authorship signals evaluated." }]);
  const crawl = scoreCategory("crawlability", [{ ok: Boolean(extractCanonicalUrl(html)), evidence: "Canonical URL detected." }, { ok: Boolean(extractTitle(html)), evidence: "Page title detected." }, { ok: Boolean(extractMetaContent(html, "description")), evidence: "Meta description detected." }, { ok: links.length >= 3, evidence: `${links.length} HTML links detected on the homepage.` }]);
  const contentStructure = scoreCategory("content_structure", [{ ok: extractHeadings(html, 1).length === 1, evidence: "Exactly one H1 heading detected." }, { ok: headings.length >= 3, evidence: "A multi-level heading structure is present." }, { ok: links.some((link) => link.text.length >= 4), evidence: "Descriptive anchor text detected." }, { ok: /<ul|<ol|<table/i.test(html), evidence: "Semantic list or table structure detected." }]);
  const categories = [identity, services, location, structured, answer, trust, crawl, contentStructure];
  const score = Math.round(categories.reduce((sum, category) => sum + category.score * AEO_WEIGHTS[category.key], 0) / 100);
  const findings = categories.filter((category) => category.score >= 70).slice(0, 4).map((category) => ({ title: `${category.label} is clearly established`, summary: category.evidence.filter((evidence) => evidence.startsWith("Pass")).slice(0, 2).join(" "), status: "pass" as const }));
  const recommendations = categories.filter((category) => category.score < 70).slice(0, 4).map((category) => ({ title: category.key === "answer_friendly_content" ? "Answer common customer questions" : category.key === "structured_data" ? "Strengthen structured business and service information" : category.key === "location_service_area" ? "Clarify where you serve customers" : category.key === "services_offerings" ? "Describe your services more clearly" : category.key === "expertise_trust" ? "Add relevant expertise and trust signals" : category.key === "business_identity" ? "Strengthen your business identity information" : category.key === "content_structure" ? "Make important answers easier to extract" : "Improve crawlable business information", description: category.evidence.filter((evidence) => evidence.startsWith("Needs attention")).slice(0, 2).join(" ") }));
  return { score, categories, questionCoverage: coverage, findings, recommendations, evidence: { profile: profile.key, schemaTypes: types, businessNameProvided: Boolean(input.businessName), auditMarket: input.market ?? null, websiteLocationEvidence: hasAddress }, checkedAt: new Date().toISOString() };
}
