import type { FindingCategory, FindingStatus } from "@/lib/audit/types";

export type RecommendationPriority = "low" | "medium" | "high" | "critical";

export type RecommendationRule = {
  recommendationKey: string;
  category: FindingCategory;
  title: string;
  description: string;
  priority: RecommendationPriority;
  impact: string;
  effort: string;
  /** Exact finding check_keys that can trigger this recommendation. */
  matchingFindingKeys: readonly string[];
  triggerStatuses: readonly FindingStatus[];
  signalworksServiceKey?: string;
  isPublic: boolean;
  isClientVisible: boolean;
};

export const RECOMMENDATION_RULES: readonly RecommendationRule[] = [
  {
    recommendationKey: "technical.review_redirect_chain",
    category: "technical",
    title: "Review homepage redirect chain",
    description:
      "Reduce unnecessary redirects on the homepage so visitors and crawlers reach content in fewer hops.",
    priority: "medium",
    impact: "Fewer redirects can improve load time and reduce crawl inefficiency.",
    effort: "Low",
    matchingFindingKeys: ["technical.redirect.chain"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "website_hosting",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.add_meta_description",
    category: "seo",
    title: "Add a homepage meta description",
    description:
      "Write a unique meta description for the homepage that summarizes your services and service area in 120–160 characters.",
    priority: "high",
    impact: "Improves click-through from search results and clarifies relevance for local queries.",
    effort: "Low",
    matchingFindingKeys: ["seo.meta_description.missing"],
    triggerStatuses: ["fail", "warning"],
    signalworksServiceKey: "local_seo",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.improve_meta_description",
    category: "seo",
    title: "Improve homepage meta description length",
    description:
      "Adjust the meta description so it is descriptive and within a typical 120–160 character range.",
    priority: "medium",
    impact: "Better search snippet presentation.",
    effort: "Low",
    matchingFindingKeys: ["seo.meta_description.present"],
    triggerStatuses: ["warning"],
    signalworksServiceKey: "local_seo",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.add_page_title",
    category: "seo",
    title: "Add a homepage title tag",
    description:
      "Add a descriptive <title> that includes the business name and primary service area.",
    priority: "high",
    impact: "Required for search engines to understand the page topic.",
    effort: "Low",
    matchingFindingKeys: ["seo.title.missing"],
    triggerStatuses: ["fail"],
    signalworksServiceKey: "local_seo",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.improve_page_title",
    category: "seo",
    title: "Improve homepage title length",
    description:
      "Refine the page title so it is clear, branded, and within a typical 20–60 character range.",
    priority: "medium",
    impact: "Improves readability in browser tabs and search results.",
    effort: "Low",
    matchingFindingKeys: ["seo.title.present"],
    triggerStatuses: ["warning"],
    signalworksServiceKey: "local_seo",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.add_localbusiness_schema",
    category: "local_seo",
    title: "Add LocalBusiness structured data",
    description:
      "Add LocalBusiness JSON-LD containing verified business name, phone, service area, hours, and profile links.",
    priority: "high",
    impact: "Supports local relevance signals and rich result eligibility (not guaranteed).",
    effort: "Medium",
    matchingFindingKeys: ["seo.localbusiness_schema.missing"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "local_seo",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.complete_localbusiness_schema",
    category: "local_seo",
    title: "Complete LocalBusiness structured data fields",
    description:
      "Ensure LocalBusiness schema includes address, phone, service area, and sameAs profile links where applicable.",
    priority: "medium",
    impact: "Improves completeness of local business signals.",
    effort: "Medium",
    matchingFindingKeys: [
      "seo.localbusiness_schema.address",
      "seo.localbusiness_schema.phone",
      "seo.localbusiness_schema.service_area",
      "seo.localbusiness_schema.same_as",
    ],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "local_seo",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.add_canonical_url",
    category: "seo",
    title: "Add a canonical URL",
    description: "Add a canonical link element pointing to the preferred homepage URL.",
    priority: "medium",
    impact: "Reduces duplicate URL confusion for search engines.",
    effort: "Low",
    matchingFindingKeys: ["seo.canonical.missing"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "local_seo",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.add_xml_sitemap",
    category: "seo",
    title: "Publish an XML sitemap",
    description:
      "Create and submit an XML sitemap, then reference it in robots.txt.",
    priority: "medium",
    impact: "Helps search engines discover important pages.",
    effort: "Medium",
    matchingFindingKeys: ["seo.sitemap.missing"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "local_seo",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.fix_robots_txt",
    category: "seo",
    title: "Review robots.txt crawl rules",
    description:
      "Ensure robots.txt does not unintentionally block important pages from crawling.",
    priority: "high",
    impact: "Blocking rules can prevent indexing of key pages.",
    effort: "Low",
    matchingFindingKeys: ["seo.robots_txt.homepage_blocked"],
    triggerStatuses: ["fail"],
    signalworksServiceKey: "local_seo",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.add_robots_txt",
    category: "seo",
    title: "Add a robots.txt file",
    description: "Publish a robots.txt file at the site root with sitemap references.",
    priority: "low",
    impact: "Provides crawl guidance to search engines.",
    effort: "Low",
    matchingFindingKeys: ["seo.robots_txt.missing"],
    triggerStatuses: ["warning"],
    signalworksServiceKey: "local_seo",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "seo.fix_h1_structure",
    category: "seo",
    title: "Fix homepage H1 heading structure",
    description:
      "Use exactly one clear H1 on the homepage that states the primary service and location focus.",
    priority: "medium",
    impact: "Improves on-page topic clarity.",
    effort: "Low",
    matchingFindingKeys: ["seo.h1.count"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "local_seo",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "conversion.add_primary_cta",
    category: "conversion",
    title: "Add a prominent primary conversion action",
    description:
      "Add a clear primary CTA above the fold (call, quote request, schedule, or contact).",
    priority: "high",
    impact: "Improves lead capture from homepage traffic.",
    effort: "Medium",
    matchingFindingKeys: ["conversion.primary_cta.present"],
    triggerStatuses: ["warning"],
    signalworksServiceKey: "website_conversion",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "conversion.improve_contact_visibility",
    category: "conversion",
    title: "Make contact information easier to find",
    description:
      "Display phone and/or email contact details prominently on the homepage.",
    priority: "high",
    impact: "Reduces friction for high-intent visitors.",
    effort: "Low",
    matchingFindingKeys: ["conversion.contact.visible"],
    triggerStatuses: ["warning"],
    signalworksServiceKey: "website_conversion",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "performance.improve_mobile_score",
    category: "performance",
    title: "Improve mobile performance score",
    description:
      "Address PageSpeed performance opportunities to improve mobile loading and interactivity.",
    priority: "high",
    impact: "Faster mobile experiences can improve engagement and conversion.",
    effort: "Medium",
    matchingFindingKeys: ["performance.mobile.score"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "website_performance",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "performance.improve_mobile_lcp",
    category: "performance",
    title: "Improve mobile loading performance (LCP)",
    description:
      "Reduce Largest Contentful Paint on mobile by optimizing hero images, fonts, and render-blocking resources.",
    priority: "high",
    impact: "LCP is a core loading metric for mobile visitors.",
    effort: "Medium",
    matchingFindingKeys: ["performance.mobile.lcp"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "website_performance",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "performance.improve_mobile_cls",
    category: "performance",
    title: "Reduce layout shift on mobile (CLS)",
    description:
      "Reserve space for images and ads and avoid late-loading elements that move page content.",
    priority: "medium",
    impact: "Improves visual stability on mobile devices.",
    effort: "Medium",
    matchingFindingKeys: ["performance.mobile.cls"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "website_performance",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "technical.enforce_https",
    category: "technical",
    title: "Enforce HTTPS across the site",
    description:
      "Redirect all HTTP traffic to HTTPS and verify certificates are valid.",
    priority: "critical",
    impact: "Protects visitors and avoids browser security warnings.",
    effort: "Low",
    matchingFindingKeys: ["technical.https.enforced"],
    triggerStatuses: ["fail"],
    signalworksServiceKey: "website_hosting",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "technical.fix_homepage_status",
    category: "technical",
    title: "Fix homepage HTTP errors",
    description: "Resolve the server error preventing a successful homepage response.",
    priority: "critical",
    impact: "Visitors and search engines cannot access the site reliably.",
    effort: "Medium",
    matchingFindingKeys: ["technical.response.status"],
    triggerStatuses: ["fail"],
    signalworksServiceKey: "website_hosting",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "security.improve_security_headers",
    category: "security",
    title: "Add basic security headers",
    description:
      "Configure HSTS, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, and CSP where appropriate.",
    priority: "medium",
    impact: "Reduces common web security risks.",
    effort: "Medium",
    matchingFindingKeys: ["security.headers.basic"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "website_security",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "security.review_dmarc_policy",
    category: "email_auth",
    title: "Review and strengthen DMARC enforcement policy",
    description:
      "Move from a none policy to quarantine or reject after reviewing SPF/DKIM alignment.",
    priority: "high",
    impact: "Reduces spoofing risk for your domain email.",
    effort: "Medium",
    matchingFindingKeys: ["security.dmarc.policy_none"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "email_authentication",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "accessibility.improve_image_alt_text",
    category: "accessibility",
    title: "Improve homepage image alt text",
    description:
      "Add descriptive alt text to homepage images that convey information or function.",
    priority: "medium",
    impact: "Improves accessibility and image context for search engines.",
    effort: "Low",
    matchingFindingKeys: ["accessibility.image_alt.coverage"],
    triggerStatuses: ["warning", "fail"],
    signalworksServiceKey: "website_accessibility",
    isPublic: false,
    isClientVisible: true,
  },
  {
    recommendationKey: "content.expand_homepage_copy",
    category: "content",
    title: "Expand thin homepage content",
    description:
      "Add clearer service, service-area, and trust content so visitors understand what you offer.",
    priority: "medium",
    impact: "Improves clarity for visitors and search relevance.",
    effort: "Medium",
    matchingFindingKeys: ["content.homepage.thin_content"],
    triggerStatuses: ["warning"],
    signalworksServiceKey: "website_content",
    isPublic: true,
    isClientVisible: true,
  },
  {
    recommendationKey: "operations.complete_inventory",
    category: "operations",
    title: "Complete Operations Inventory documentation",
    description:
      "Document hosting, DNS, backups, and service ownership in the Signal Works Operations Inventory.",
    priority: "medium",
    impact: "Improves operational visibility and incident response readiness.",
    effort: "Low",
    matchingFindingKeys: [
      "operations.inventory.missing",
      "operations.registrar.recorded",
      "operations.dns.recorded",
      "operations.hosting.recorded",
      "operations.backups.unknown",
    ],
    triggerStatuses: ["manual_review", "warning", "fail"],
    signalworksServiceKey: "managed_operations",
    isPublic: false,
    isClientVisible: true,
  },
] as const;

export const RECOMMENDATION_CATALOG_VERSION = "1.0.0";
